#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Droid_PeopleWithParkinsons.Resource", IsApplication=true)]

namespace Droid_PeopleWithParkinsons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int scale_button_normal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int scale_button_pressed = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int minTextSize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int darkBlue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lightBlue = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_pressed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_unpressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int driver = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_mic = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int listCell = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int recordButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int round_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int round_button_alt = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001b
			public const int BackgroundAudioDisplay = 2131296283;
			
			// aapt resource value: 0x7f090014
			public const int CheckBoxLowerHeader = 2131296276;
			
			// aapt resource value: 0x7f090010
			public const int CircleWaveForm = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int FlagAudio = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int Instructions = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int PlaybackButtonRoot = 2131296273;
			
			// aapt resource value: 0x7f090019
			public const int RecordButton = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int RecordCompletedConfirmButton = 2131296277;
			
			// aapt resource value: 0x7f09000b
			public const int RecordCompletedHeader = 2131296267;
			
			// aapt resource value: 0x7f090012
			public const int RecordCompleted_ButtonText = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int RecordCompleted_FramePaddingLeft = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int RecordCompleted_FrameRecorderSet = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int RecordCompleted_LinearRecorderRoot = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int RecordSoundHeaderLower = 2131296268;
			
			// aapt resource value: 0x7f09001c
			public const int RecordSoundRunFragment = 2131296284;
			
			// aapt resource value: 0x7f090016
			public const int RootLayout = 2131296278;
			
			// aapt resource value: 0x7f09001a
			public const int StoredSoundsValue = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int TextToSpeak = 2131296280;
			
			// aapt resource value: 0x7f090001
			public const int fragmentContainer = 2131296257;
			
			// aapt resource value: 0x7f090027
			public const int help = 2131296295;
			
			// aapt resource value: 0x7f090002
			public const int left_drawer = 2131296258;
			
			// aapt resource value: 0x7f09000a
			public const int mainActivitiesList = 2131296266;
			
			// aapt resource value: 0x7f090003
			public const int mainDrawerList = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int mainFriendListAvatar = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int mainFriendListName = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int mainFriendsList = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int mainListActivityIcon = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int mainListActivityTitle = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int mainListLastTime = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int mainMenuDrawerLayout = 2131296256;
			
			// aapt resource value: 0x7f09001f
			public const int scenarioAuthor = 2131296287;
			
			// aapt resource value: 0x7f090026
			public const int scenarioBreaker = 2131296294;
			
			// aapt resource value: 0x7f090021
			public const int scenarioEventLayout = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int scenarioImage = 2131296290;
			
			// aapt resource value: 0x7f090025
			public const int scenarioProgressBtn = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int scenarioPrompt = 2131296292;
			
			// aapt resource value: 0x7f090020
			public const int scenarioStartBtn = 2131296288;
			
			// aapt resource value: 0x7f090023
			public const int scenarioText = 2131296291;
			
			// aapt resource value: 0x7f09001e
			public const int scenarioTitle = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int scenarioTitleLayout = 2131296285;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainFriendListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainFriendsListFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenuListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainTaskListFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RecordCompleted = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RecordSound = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RecordSoundRun = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ScenarioFragment = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int RecordMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int appTitleMain = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutoResizeTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int AutoResizeTextView_minTextSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
