#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Droid_PeopleWithParkinsons.Resource", IsApplication=true)]

namespace Droid_PeopleWithParkinsons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int scale_button_normal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int scale_button_pressed = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int minTextSize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_pressed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_unpressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_mic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int listCell = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int recordButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int round_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int round_button_alt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int BackgroundAudioDisplay = 2131230747;
			
			// aapt resource value: 0x7f080014
			public const int CheckBoxLowerHeader = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int CircleWaveForm = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int FlagAudio = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int Instructions = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int PlaybackButtonRoot = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int RecordButton = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int RecordCompletedConfirmButton = 2131230741;
			
			// aapt resource value: 0x7f08000b
			public const int RecordCompletedHeader = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int RecordCompleted_ButtonText = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int RecordCompleted_FramePaddingLeft = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int RecordCompleted_FrameRecorderSet = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int RecordCompleted_LinearRecorderRoot = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int RecordSoundHeaderLower = 2131230732;
			
			// aapt resource value: 0x7f08001c
			public const int RecordSoundRunFragment = 2131230748;
			
			// aapt resource value: 0x7f080016
			public const int RootLayout = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int StoredSoundsValue = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int TextToSpeak = 2131230744;
			
			// aapt resource value: 0x7f080001
			public const int fragmentContainer = 2131230721;
			
			// aapt resource value: 0x7f08001d
			public const int help = 2131230749;
			
			// aapt resource value: 0x7f080002
			public const int left_drawer = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int mainActivitiesList = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int mainDrawerList = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int mainFriendListAvatar = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int mainFriendListName = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int mainFriendsList = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int mainListActivityIcon = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int mainListActivityTitle = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int mainListLastTime = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int mainMenuDrawerLayout = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainFriendListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainFriendsListFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenuListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainTaskListFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RecordCompleted = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RecordSound = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RecordSoundRun = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int RecordMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int appTitleMain = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutoResizeTextView = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int AutoResizeTextView_minTextSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
