#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Droid_PeopleWithParkinsons.Resource", IsApplication=true)]

namespace Droid_PeopleWithParkinsons
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int scale_button_normal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int scale_button_pressed = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_mic = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int round_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int round_button_alt = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int AnalyseBtn = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int BackgroundAudioDisplay = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int CircleWaveForm = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int FlagAudio = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int RecordBtn = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int RecordCompletedConfirmButton = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int RecordCompletedHeader = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int RecordSoundBtn = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int RecordSoundHeaderLower = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int RecordTitleMain = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int ResultsBtn = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int RoundPlayButton = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int RoundSoundRecorderBtn = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int StoredSoundsValue = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int TitleMain = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int frameLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RecordCompleted = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RecordSound = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RecordTitle = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int appTitleMain = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
